"""API 路由汇总（在 main.py 以 /api 前缀挂载；WS 路由单独挂在根路径）。"""

from fastapi import APIRouter

from app.api import (
    admin_codes,
    admin_llm,
    admin_settings,
    admin_users,
    auth,
    chat_agent,
    chat_bots,
    concepts,
    daily,
    download_client,
    evidence,
    experiments,
    feedback,
    gates,
    health,
    highlights,
    ideas,
    ingest,
    integration_tokens,
    interdisciplinary,
    invites,
    lab,
    libraries,
    library,
    literature_discovery,
    manuscripts,
    market,
    mcp_meta,
    me_llm,
    notes,
    paper_assets,
    papers,
    presentations,
    projects,
    publications,
    search,
    shelf,
    skills,
    ssh_credentials,
    structured_content,
    tts,
    users_profile,
    views,
    voyages,
    wiki,
)
from app.integrations.deepseek_harness.api import router as deepseek_harness_router

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(views.router)
api_router.include_router(chat_agent.router)
api_router.include_router(auth.router)
api_router.include_router(chat_bots.router)
api_router.include_router(users_profile.router)
api_router.include_router(invites.router)
api_router.include_router(admin_users.router)
api_router.include_router(admin_codes.router)
api_router.include_router(feedback.router)
api_router.include_router(projects.router)
api_router.include_router(gates.router)
api_router.include_router(voyages.router)
api_router.include_router(admin_llm.router)
api_router.include_router(admin_settings.router)
api_router.include_router(lab.router)
api_router.include_router(me_llm.router)
api_router.include_router(papers.router)
api_router.include_router(library.router)
api_router.include_router(literature_discovery.router)
api_router.include_router(paper_assets.router)
api_router.include_router(structured_content.router)
api_router.include_router(libraries.router)
api_router.include_router(publications.router)
api_router.include_router(notes.router)
api_router.include_router(highlights.router)
api_router.include_router(concepts.router)
api_router.include_router(ingest.router)
api_router.include_router(interdisciplinary.router)
api_router.include_router(interdisciplinary.suggestion_router)
api_router.include_router(integration_tokens.router)
api_router.include_router(wiki.router)
api_router.include_router(ideas.router)
api_router.include_router(search.router)
api_router.include_router(shelf.router)
api_router.include_router(daily.router)
api_router.include_router(download_client.router)
api_router.include_router(deepseek_harness_router)
api_router.include_router(skills.router)
api_router.include_router(market.router)
api_router.include_router(mcp_meta.router)
api_router.include_router(presentations.router)
api_router.include_router(ssh_credentials.router)
api_router.include_router(tts.router)
api_router.include_router(evidence.router)
api_router.include_router(experiments.router)
api_router.include_router(manuscripts.router)
